import { MusicInfo } from './control-panel/music-info.model';
import { GenreInfo } from './genre.model';
import { Playlist } from './playlist.model';

export const musicData: MusicInfo[] = [
  {
    id: '0',
    name: 'Knee Socks',
    author: 'Arctic Monkeys',
    album: 'AM',
    logo: `./examples/music/Arctic Monkeys/AM.png`,
    path: `./examples/music/Arctic Monkeys/Arctic Monkeys - Knee Socks.mp3`,
  },
  {
    id: '1',
    name: 'Too Sweet',
    author: 'Hozier',
    album: 'Unheard',
    logo: `./examples/music/Hozier/Unheard.png`,
    path: './examples/music/Hozier/Hozier - Too Sweet.mp3',
  },
  {
    id: '2',
    name: 'Roots',
    author: 'Imagine Dragons',
    album: 'Roots',
    logo: `./examples/music/Imagine Dragons/Roots.png`,
    path: './examples/music/Imagine Dragons/Imagine Dragons - Roots.mp3',
  },
  {
    id: '3',
    name: 'Higher Ground',
    author: 'Imagine Dragons',
    album: 'Mercury',
    logo: `./examples/music/Imagine Dragons/Mercury.png`,
    path: './examples/music/Imagine Dragons/Imagine Dragons - Higher Ground.mp3',
  },
  {
    id: '4',
    name: 'Do I Wanna Know',
    author: 'Arctic Monkeys',
    album: 'AM',
    logo: `./examples/music/Arctic Monkeys/AM.png`,
    path: './examples/music/Arctic Monkeys/Arctic Monkeys - Do I Wanna Know.mp3',
  },
  {
    id: '5',
    name: 'Take Me To Church',
    author: 'Hozier',
    album: 'Hozier',
    logo: `./examples/music/Hozier/Hozier.png`,
    path: './examples/music/Hozier/Hozier - Take Me To Church.mp3',
  },
  {
    id: '6',
    name: 'Get Around Town',
    author: 'Revolver',
    album: 'Music for a While',
    logo: `./examples/music/Revolver/Music for a While.png`,
    path: './examples/music/Revolver/Revolver - Get Around Town.mp3',
  },
  {
    id: '7',
    name: 'Riptide',
    author: 'Vance Joy',
    album: `God Loves You When You're Dancing`,
    logo: `./examples/music/Vance Joy/God Loves You When You're Dancing.png`,
    path: './examples/music/Vance Joy/Vance Joy - Riptide.mp3',
  },
  {
    id: '8',
    name: 'Sing To Me',
    author: 'Missio',
    album: `Death Stranding Timefall`,
    logo: `./examples/music/Missio/Death Stranding Timefall.png`,
    path: './examples/music/Missio/Missio - Sing To Me.mp3',
  },
  {
    id: '9',
    name: 'Burn Out',
    author: 'Imagine Dragons',
    album: `Origins`,
    logo: `./examples/music/Imagine Dragons/Origins.png`,
    path: './examples/music/Imagine Dragons/Imagine Dragons - Burn Out.mp3',
  },
  {
    id: '10',
    name: 'Just The Two Of Us',
    author: 'Grover Washington Jr',
    album: `Winelight`,
    logo: `./examples/music/Grover Washington Jr/Winelight.png`,
    path: './examples/music/Grover Washington Jr/Grover Washington Jr - Just The Two Of Us.mp3',
  },
  {
    id: '11',
    name: `C'mon Down`,
    author: `Poor Man's Poison`,
    album: `Providence`,
    logo: `./examples/music/Poor Man's Poison/Providence.png`,
    path: `./examples/music/Poor Man's Poison/Poor Man's Poison - C'mon Down.mp3`,
  },
  {
    id: '12',
    name: `The Moss`,
    author: 'Cosmo Sheldrake',
    album: `Old Tunes EP`,
    logo: `./examples/music/Cosmo Sheldrake/Old Tunes EP.png`,
    path: `./examples/music/Cosmo Sheldrake/Cosmo Sheldrake - The Moss.mp3`,
  },
  {
    id: '13',
    name: `Can't Stop`,
    author: 'Red Hot Chili Peppers',
    album: `By the Way`,
    logo: `./examples/music/Red Hot Chili Peppers/By the Way.png`,
    path: `./examples/music/Red Hot Chili Peppers/Red Hot Chili Peppers - Can't Stop.mp3`,
  },
];

export const genres: GenreInfo[] = [
  {
    id: '0',
    name: `Rock`,
    logo: `./examples/genres/Rock.png`,
  },
  {
    id: '1',
    name: `Classical`,
    logo: `./examples/genres/Classical.png`,
  },
  {
    id: '2',
    name: `Country`,
    logo: `./examples/genres/Country.png`,
  },
  {
    id: '3',
    name: `Hip-Hop`,
    logo: `./examples/genres/Hip-Hop.png`,
  },
  {
    id: '4',
    name: `Indie`,
    logo: `./examples/genres/Indie.png`,
  },
  {
    id: '5',
    name: `Chill`,
    logo: `./examples/genres/Chill.png`,
  },
  {
    id: '6',
    name: `K-Pop`,
    logo: `./examples/genres/K-Pop.png`,
  },
  {
    id: '7',
    name: `Dance`,
    logo: `./examples/genres/Dance.png`,
  },
  {
    id: '8',
    name: `Party`,
    logo: `./examples/genres/Party.png`,
  },
  {
    id: '9',
    name: `Blues`,
    logo: `./examples/genres/Blues.png`,
  },
  {
    id: '10',
    name: `Sleep`,
    logo: `./examples/genres/Sleep.png`,
  },
  {
    id: '11',
    name: `Pop`,
    logo: `./examples/genres/Pop.png`,
  },
];

export const playlists: Playlist[] = [
  {
    id: '0',
    name: 'Rock',
    logo: './examples/playlists/Rock.png',
    author: 'eltso_',
    description: 'Rock Music Playlist',
    songs: ['0', '1', '2'],
  },
  {
    id: '1',
    name: 'Pop',
    logo: './examples/playlists/Pop.png',
    author: 'eltso_',
    description: 'Pop Music Playlist',
    songs: ['0', '1', '2'],
  },
  {
    id: '2',
    name: 'Indie',
    logo: './examples/playlists/Indie.png',
    author: 'eltso_',
    description: 'Indie Music Playlist',
    songs: ['0', '1', '2'],
  },
  {
    id: '3',
    name: 'Acoustic',
    logo: './examples/playlists/Acoustic.png',
    author: 'eltso_',
    description: 'Acoustic Music Playlist',
    songs: ['0', '1', '2'],
  },
  {
    id: '4',
    name: 'Country',
    logo: './examples/playlists/Country.png',
    author: 'eltso_',
    description: 'Country Music Playlist',
    songs: ['0', '1', '2'],
  },
  {
    id: '5',
    name: 'Hip-Hop',
    logo: './examples/playlists/Hip-Hop.png',
    author: 'eltso_',
    description: 'Hip-Hop Music Playlist',
    songs: ['0', '1', '2'],
  },
];
